olark.declare({name:"CalloutBubble",version:"1.0",startup:function(i,b){function o(a,c){var b={duration:1E3,interval:10,from:0,to:100,easingFunc:function(a,d,c){var b=0;b=(c/=1)<1/2.75?1*7.5625*c*c+0:c<2/2.75?1*(7.5625*(c-=1.5/2.75)*c+0.75)+0:c<2.5/2.75?1*(7.5625*(c-=2.25/2.75)*c+0.9375)+0:1*(7.5625*(c-=2.625/2.75)*c+0.984375)+0;return a+(d-a)*b}},f;for(f in c)c.hasOwnProperty(f)&&(b[f]=c[f]);var e=[],g=b.duration/b.interval;for(f=0;f<g;++f)e.push(b.easingFunc(b.from,b.to,f/g));for(f=0;f<e.length;++f)(function(){setTimeout(function(){a.style.height=
parseInt(e.shift())+"px"},b.interval*f)})(e[f])}function p(a,c,b,f){if(a)if(!c&&!b){var e=new Image,g=!1,h=function(){b=parseInt(e.height);c=parseInt(e.width);!g&&b&&c&&(f(c,b),g=!0)};e.onload=h;e.src=a;h()}else c&&b&&f(c,b);else f(c,b)}function s(d){p(a.BUBBLE_IMAGE_URL,a.BUBBLE_WIDTH,a.BUBBLE_HEIGHT,function(c,b){a.BUBBLE_HEIGHT=b||a.DEFAULT_HEIGHT;a.BUBBLE_WIDTH=c||a.DEFAULT_WIDTH;p(a.BUBBLE_IMAGE_URL_OFFLINE,a.BUBBLE_WIDTH_OFFLINE,a.BUBBLE_HEIGHT_OFFLINE,function(c,b){a.BUBBLE_HEIGHT_OFFLINE=
b||a.DEFAULT_HEIGHT;a.BUBBLE_WIDTH_OFFLINE=c||a.DEFAULT_WIDTH;a.BUBBLE_BOTTOM_OFFSET=a.BUBBLE_BOTTOM_OFFSET||0;a.BUBBLE_TOP_OFFSET=a.BUBBLE_TOP_OFFSET||0;a.BUBBLE_LEFT_OFFSET=a.BUBBLE_LEFT_OFFSET||a.OFFSET.left;a.BUBBLE_RIGHT_OFFSET=a.BUBBLE_RIGHT_OFFSET||a.OFFSET.right;a.BUBBLE_BOTTOM_OFFSET_OFFLINE=0;a.BUBBLE_TOP_OFFSET_OFFLINE=0;a.BUBBLE_LEFT_OFFSET_OFFLINE=a.BUBBLE_LEFT_OFFSET_OFFLINE||a.OFFSET_OFFLINE.left;a.BUBBLE_RIGHT_OFFSET_OFFLINE=a.BUBBLE_RIGHT_OFFSET_OFFLINE||a.OFFSET_OFFLINE.right;d()})})}
function t(){u.id="habla-callout-container";e.id="habla-callout-bubble-anchor";j.id="habla-callout-bubble-anchor-offline";g.id="olark-callout-bubble";h.id="olark-callout-bubble-offline";e.href="#";j.href="#";(function(d){d=d||function(){return!1};e.onclick=function(){a.CLICKED.set(!0);i.box.expand();a.HIDE_WHEN_CLICKED&&a.CLICKED.get()&&m();return d()}})(e.onclick);(function(d){d=d||function(){return!1};k.onclick=function(c){a.X_CLICKED.set(!0);if(a.HIDE_WHEN_X_CLICKED&&a.X_CLICKED.get()){m();if(!c)c=
window.event;c.cancelBubble=!0;c.stopPropagation&&c.stopPropagation()}return d()}})(k.onclick);(function(d){d=d||function(){return!1};j.onclick=function(){a.CLICKED.set(!0);i.box.expand();a.HIDE_WHEN_CLICKED&&a.CLICKED.get()&&m();return d()}})(j.onclick);(function(d){d=d||function(){return!1};l.onclick=function(c){a.X_CLICKED.set(!0);if(a.HIDE_WHEN_X_CLICKED&&a.X_CLICKED.get()){m();if(!c)c=window.event;c.cancelBubble=!0;c.stopPropagation&&c.stopPropagation()}return d()}})(l.onclick);window.addEventListener&&
!window.opera?(g.addEventListener("mouseover",function(){k.className="olark-callout-bubble-close-button"},!1),h.addEventListener("mouseover",function(){l.className="olark-callout-bubble-close-button"},!1)):window.attachEvent?(g.attachEvent("onmouseover",function(){k.className="olark-callout-bubble-close-button"}),h.attachEvent("onmouseover",function(){l.className="olark-callout-bubble-close-button"})):(g.onmouseover=function(){k.className="olark-callout-bubble-close-button"},h.onmouseover=function(){l.className=
"olark-callout-bubble-close-button"});window.addEventListener&&!window.opera?(g.addEventListener("mouseout",function(){k.className=""},!1),h.addEventListener("mouseout",function(){l.className=""},!1)):window.attachEvent?(g.attachEvent("onmouseout",function(){k.className=""}),h.attachEvent("onmouseout",function(){l.className=""})):(h.onmouseout=function(){l.className=""},g.onmouseout=function(){k.className=""});e.appendChild(g);g.appendChild(k);j.appendChild(h);h.appendChild(l)}function q(){var d=
!a.BUBBLE_IMAGE_URL||a.BUBBLE_IMAGE_URL=="";a.HIDE_WHEN_CLICKED&&a.CLICKED.get()||d?m():a.HIDE_WHEN_X_CLICKED&&a.X_CLICKED.get()?m():(e.style.display="block",j.style.display="none");d=e.firstChild;if(!a.SLID.get()&&a.BUBBLE_SLIDE_EFFECT)d.style.visibility="hidden",d.style.height=0;g.style.display="block";h.style.display="none";!a.SLID.get()&&a.BUBBLE_SLIDE_EFFECT&&v()}function r(){var d=!a.BUBBLE_IMAGE_URL_OFFLINE||a.BUBBLE_IMAGE_URL_OFFLINE=="";a.HIDE_WHEN_CLICKED&&a.CLICKED.get()||d?m():a.HIDE_WHEN_X_CLICKED&&
a.X_CLICKED.get()?m():(e.style.display="none",j.style.display="block")}function m(){e.style.display="none";j.style.display="none";var a=document.getElementById("habla_compressed_div");a.style.height=null;a.style.width=null}function v(){var b=e.firstChild,c={to:parseInt(a.BUBBLE_HEIGHT),duration:750};setTimeout(function(){b.style.visibility="visible";o(b,c);n()},2E3);a.SLID.set(!0)}function n(){clearTimeout(a.IDLE_TIMEOUT);a.IDLE_TIMEOUT=setTimeout(function(){var b={from:parseInt(a.BUBBLE_HEIGHT)+
20,to:parseInt(a.BUBBLE_HEIGHT),duration:750};o(e.firstChild,b);n()},2E4)}var a={};a.DEFAULT_WIDTH=164;a.DEFAULT_HEIGHT=153;a.PROTOCOL=document.location.protocol=="https:"?"https:":"http:";a.DEFAULT_IMAGE_PATH=a.PROTOCOL+"//static.olark.com/images/thisisolark-trans.png";a.CLOSE_BUTTON_IMAGE_PATH=a.PROTOCOL+"//static.olark.com/images/close.png";a.BUBBLE_IMAGE_URL=b.CalloutBubble.bubble_image_url!=void 0?b.CalloutBubble.bubble_image_url:a.DEFAULT_IMAGE_PATH;a.BUBBLE_IMAGE_URL_OFFLINE=b.CalloutBubble.offline_bubble_image_url||
b.CalloutBubble.bubble_image_url_offline||void 0;a.BUBBLE_HEIGHT=b.CalloutBubble.bubble_height||void 0;a.BUBBLE_WIDTH=b.CalloutBubble.bubble_width||void 0;a.BUBBLE_HEIGHT_OFFLINE=b.CalloutBubble.bubble_height_offline||void 0;a.BUBBLE_WIDTH_OFFLINE=b.CalloutBubble.bubble_width_offline||void 0;a.BUBBLE_BOTTOM_OFFSET=b.CalloutBubble.bubble_bottom_offset||void 0;a.BUBBLE_TOP_OFFSET=b.CalloutBubble.bubble_top_offset||void 0;a.BUBBLE_RIGHT_OFFSET=b.CalloutBubble.bubble_right_offset||void 0;a.BUBBLE_LEFT_OFFSET=
b.CalloutBubble.bubble_left_offset||void 0;a.BUBBLE_BOTTOM_OFFSET_OFFLINE=b.CalloutBubble.bubble_bottom_offset_offline||void 0;a.BUBBLE_TOP_OFFSET_OFFLINE=b.CalloutBubble.bubble_top_offset_offline||void 0;a.BUBBLE_RIGHT_OFFSET_OFFLINE=b.CalloutBubble.bubble_right_offset_offline||void 0;a.BUBBLE_LEFT_OFFSET_OFFLINE=b.CalloutBubble.bubble_left_offset_offline||void 0;a.OFFSET=b.CalloutBubble.offset||{};a.OFFSET_OFFLINE=b.CalloutBubble.offset_offline||{};a.OFFSET.top=a.OFFSET.top||0;a.OFFSET.bottom=a.OFFSET.bottom||
0;a.OFFSET.left=a.OFFSET.left||0;a.OFFSET.right=a.OFFSET.right||0;a.OFFSET_OFFLINE.top=a.OFFSET_OFFLINE.top||0;a.OFFSET_OFFLINE.bottom=a.OFFSET_OFFLINE.bottom||0;a.OFFSET_OFFLINE.left=a.OFFSET_OFFLINE.left||0;a.OFFSET_OFFLINE.right=a.OFFSET_OFFLINE.right||0;a.BUBBLE_SLIDE_EFFECT=b.CalloutBubble.slide||!1;a.HIDE_WHEN_CLICKED=b.CalloutBubble.hide_when_clicked||!1;a.HIDE_WHEN_X_CLICKED=b.CalloutBubble.hide_when_x_clicked||!0;a.IDLE_TIMEOUT=void 0;a.CLICKED=i.data.getConversationObject({key:"bubble-clicked",
initialValue:!1});a.X_CLICKED=i.data.getConversationObject({key:"bubble-x-clicked",initialValue:!1});a.LOADED=!1;a.SLID=i.data.getConversationObject({key:"bubble-slid",initialValue:!1});a.SSL_PAGE=a.PROTOCOL=="https:";if(a.SSL_PAGE){if(a.BUBBLE_IMAGE_URL)a.BUBBLE_IMAGE_URL=a.BUBBLE_IMAGE_URL.replace("http:","https:");if(a.BUBBLE_IMAGE_URL_OFFLINE)a.BUBBLE_IMAGE_URL_OFFLINE=a.BUBBLE_IMAGE_URL_OFFLINE.replace("http:","https:")}var w=document.compatMode=="BackCompat",u=document.createElement("div"),
e=document.createElement("a"),j=document.createElement("a"),g=document.createElement("div"),h=document.createElement("div"),k=document.createElement("div"),l=document.createElement("div");i.chat.onOperatorsAvailable(function(){a.LOADED&&(a.HIDE_WHEN_CLICKED&&a.CLICKED.set(!1),a.BUBBLE_SLIDE_EFFECT&&a.SLID.set(!1),q())});i.chat.onOperatorsAway(function(){r()});i.chat.onReady(function(){t();s(function(){var b=document.getElementById("habla_compressed_div"),c=document.getElementById("habla_panel_div");
if(window.opera)b.style.height=parseInt(a.BUBBLE_HEIGHT)+"px";if(w)b.style.height=parseInt(a.BUBBLE_HEIGHT+10)+"px",b.style.width=parseInt(c.offsetWidth)+"px";b=["#habla_window_div {z-index:5000;}#habla_window_div #habla-callout-bubble-anchor,#habla_window_div #habla-callout-bubble-anchor-offline {margin: 0px;padding: 0px;border: 0px;}#habla_compressed_div {position: relative;}#habla_window_div .olark-callout-bubble-close-button {height: 20px;width: 20px;position: absolute;top: 0px;right: 0px;","background: transparent url("+
a.CLOSE_BUTTON_IMAGE_PATH+") top right no-repeat;","z-index:5001}#habla_window_div #olark-callout-bubble,#habla_window_div #olark-callout-bubble-offline {position: absolute;cursor: pointer;}#habla_window_div #olark-callout-bubble {","height: "+parseInt(a.BUBBLE_HEIGHT)+"px;","width: "+parseInt(a.BUBBLE_WIDTH)+"px;","}.olrk-fixed-bottom #olark-callout-bubble {",a.BUBBLE_IMAGE_URL?"background: transparent url("+a.BUBBLE_IMAGE_URL+") center top no-repeat;":"","z-index:5000;position:relative;}.olrk-fixed-top #olark-callout-bubble {",
a.BUBBLE_IMAGE_URL?"background: transparent url("+a.BUBBLE_IMAGE_URL+") center bottom no-repeat;":"","z-index:5000;position:relative;}#habla_window_div #olark-callout-bubble-offline {","height: "+parseInt(a.BUBBLE_HEIGHT_OFFLINE)+"px;","width: "+parseInt(a.BUBBLE_WIDTH_OFFLINE)+"px;","}.olrk-fixed-bottom #olark-callout-bubble-offline {",a.BUBBLE_IMAGE_URL_OFFLINE?"background: transparent url("+a.BUBBLE_IMAGE_URL_OFFLINE+") center top no-repeat;":"","z-index:5000;position:relative;}.olrk-fixed-top #olark-callout-bubble-offline {",
a.BUBBLE_IMAGE_URL_OFFLINE?"background: transparent url("+a.BUBBLE_IMAGE_URL_OFFLINE+") center bottom no-repeat;":"","z-index:5000;position:relative;}.olrk-fixed-top #olark-callout-bubble {","top: "+parseInt(a.BUBBLE_TOP_OFFSET)+"px;","}.olrk-fixed-bottom #olark-callout-bubble {","bottom: "+parseInt(a.BUBBLE_BOTTOM_OFFSET)+"px;","}.olrk-fixed-left #olark-callout-bubble {","right: "+parseInt(a.BUBBLE_LEFT_OFFSET)+"px;","}.olrk-fixed-right #olark-callout-bubble {","left: "+parseInt(a.BUBBLE_RIGHT_OFFSET)+
"px;","}.olrk-fixed-left .olrk-left-align #olark-callout-bubble {","left: "+parseInt(a.BUBBLE_RIGHT_OFFSET)+"px;","}.olrk-fixed-top #olark-callout-bubble-offline {","top: "+parseInt(a.BUBBLE_TOP_OFFSET_OFFLINE)+"px;","}.olrk-fixed-bottom #olark-callout-bubble-offline {","bottom: "+parseInt(a.BUBBLE_BOTTOM_OFFSET_OFFLINE)+"px;","}.olrk-fixed-left #olark-callout-bubble-offline {","right: "+parseInt(a.BUBBLE_LEFT_OFFSET_OFFLINE)+"px;","}.olrk-fixed-right #olark-callout-bubble-offline {","left: "+parseInt(a.BUBBLE_RIGHT_OFFSET_OFFLINE)+
"px;","}.olrk-fixed-left .olrk-left-align #olark-callout-bubble-offline {","left: "+parseInt(a.BUBBLE_RIGHT_OFFSET_OFFLINE)+"px;","}#habla_window_div a:hover {background-color:transparent;}#habla_available_div {display: none;}"].join("");c=document.createElement("style");c.type="text/css";c.styleSheet?c.styleSheet.cssText=b:c.appendChild(document.createTextNode(b));i.box.__SPI_injectStyleIntoPage(c);if(!a.SLID.get()&&a.BUBBLE_SLIDE_EFFECT)b=e.firstChild,b.style.visibility="hidden",b.style.height=
0;b=document.getElementById("habla_compressed_div");b.appendChild(e);b.appendChild(j);hbl.client.opavailable&&hbl.client.opstatus!="away"?q():r();if(a.BUBBLE_SLIDE_EFFECT)try{window.addEventListener("mousemove",n,!1)}catch(g){try{document.attachEvent("onmousemove",n)}catch(f){}}a.LOADED=!0})})}});
